"""Construct objective-informed hierarchies for Owen-value explanations.

The hierarchy represents relationships among objective functions using
objective values of solutions generated by the interactive optimization
method. The resulting objective hierarchy can be mapped to the
corresponding reference-point components and supplied to SHAP's
PartitionExplainer as a hierarchical coalition structure.

Several correlation and distance definitions are supported to enable
comparison of alternative representations of objective relationships.
"""

from __future__ import annotations

from typing import Literal

import numpy as np
from scipy.cluster.hierarchy import linkage
from scipy.spatial.distance import squareform
from scipy.stats import rankdata


CorrelationMethod = Literal[
    "pearson",
    "spearman",
]

DistanceMethod = Literal[
    "relationship",
    "conflict",
]


def compute_objective_correlation(
    solution_values: np.ndarray,
    *,
    method: CorrelationMethod = "spearman",
) -> np.ndarray:
    """Compute correlations among solution objective values."""
    values = np.asarray(
        solution_values,
        dtype=float,
    )

    if values.ndim != 2:
        raise ValueError(
            "solution_values must be a two-dimensional array."
        )

    if method == "pearson":
        correlation = np.corrcoef(
            values,
            rowvar=False,
        )

    elif method == "spearman":
        ranked = np.apply_along_axis(
            rankdata,
            0,
            values,
        )
        correlation = np.corrcoef(
            ranked,
            rowvar=False,
        )

    else:
        raise ValueError(
            f"Unsupported correlation method: {method}"
        )

    return np.asarray(
        correlation,
        dtype=float,
    )


def correlation_to_distance(
    correlation: np.ndarray,
    *,
    method: DistanceMethod = "conflict",
) -> np.ndarray:
    """Convert objective correlations to hierarchical distances."""
    correlation = np.asarray(
        correlation,
        dtype=float,
    )

    if method == "relationship":
        distance = 1.0 - np.abs(correlation)

    elif method == "conflict":
        distance = (1.0 + correlation) / 2.0

    else:
        raise ValueError(
            f"Unsupported distance method: {method}"
        )

    distance = np.clip(
        distance,
        0.0,
        1.0,
    )

    # Remove small numerical asymmetries.
    distance = (
        distance + distance.T
    ) / 2.0

    np.fill_diagonal(
        distance,
        0.0,
    )

    return distance


def build_objective_hierarchy(
    solution_values: np.ndarray,
    *,
    correlation_method: CorrelationMethod = "spearman",
    distance_method: DistanceMethod = "conflict",
    linkage_method: str = "average",
) -> np.ndarray:
    """Construct a MOO-informed hierarchical linkage matrix."""
    correlation = compute_objective_correlation(
        solution_values,
        method=correlation_method,
    )

    distance = correlation_to_distance(
        correlation,
        method=distance_method,
    )

    condensed_distance = squareform(
        distance,
        checks=True,
    )

    return linkage(
        condensed_distance,
        method=linkage_method,
    )
